framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            #async: '%env(MESSENGER_TRANSPORT_DSN)%'
            notification:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Infrastructure\Serializer\NotificationJsonMessageSerializer
                options:
                    exchange:
                        name: notification
                        default_publish_routing_key: notification
                    queues:
                        notification:
                            binding_keys: [ notification ]

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Application\Command\Notification\NotificationCommand': notification

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
