version: '3.3'

services:
    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            - ./:/var/www
        networks:
            - test_network
        depends_on:
            - postgresdb
    nginx:
        build:
            context: docker/nginx
            args:
                USER_ID: ${UID-1000}
                GROUP_ID: ${GID-1000}
        volumes:
            - ./:/var/www/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx
        depends_on:
            - php-fpm
        ports:
            - "8002:80"
            - "443:443"
        networks:
            - test_network

    encore:
        build:
            context: ./docker/encore
            args:
                USER_ID: ${UID-1000}
        volumes:
            - ./:/var/www
        networks:
            - test_network
        tty: true
    postgresdb:
        build:
            context: ./docker/postgres
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: postgresuser
            POSTGRES_PASSWORD: postgresuser
            POSTGRES_HOST: localhost
            PGDATA: /var/lib/postgresql/data

        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./docker/pgdata:/var/lib/postgresql/data
        networks:
            - test_network
    rabbit:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - test_network
networks:
    rabbitmq_go_net:
        driver: bridge
    test_network:
